### ISSUE TITLE
No dmesg entry to confirm device in upload mode

### ISSUE THREAD

**Issue by lemonlemming** [ddvk/remarkable-uuuflash#14]
Hi, 

Have tried the following without success in getting dmesg to show generic-hid device entry 

rm1 is connected via usb cable (have tried a different cable as well)
press/hold power button for 10s to power off device
press/hold power and middle button for >3 seconds to enter upload mode
check sudo dmesg --> no entry found similar to " hid-generic 0003:15A2:0063.0008: hiddev1,hidraw3: USB HID v1.10 Device [Freescale SemiConductor Inc  SE Blank MEGREZ] on usb-0000:00:1a.0-1.3/input0" on the readme

Any advice?

**Comment by Eeems** [comment]
Are there any usb related entries? I just tried with my device, and it works as expected. Have you confirmed that your usb cables support data transfer?

**Comment by lemonlemming** [comment]
when I check system report there's a USB device showing this:
```
SE Blank MEGREZ:

  Product ID:	0x0063
  Vendor ID:	0x15a2  (Freescale Semiconductor, Inc.)
  Version:	0.01
  Speed:	Up to 480 Mb/s
  Manufacturer:	Freescale SemiConductor Inc 
  Location ID:	0x14233000 / 8
  Current Available (mA):	500
  Current Required (mA):	10
  Extra Operating Current (mA):	0
```

Is it safe to assume this is it?

**Comment by Eeems** [comment]
That would be it. As for why it's not showing on dmesg, that would depend on your kernel's configuration, as well as the actual OS you are running on your computer. I know that macOS has completely different dmesg output.

**Comment by lemonlemming** [comment]
```
 remarkable-uuuflash % sudo uuu recover.uuu
Password:
uuu (Universal Update Utility) for nxp imx chips -- libuuu_1.5.165-0-g7347a80

Success 1    Failure 0                                                              
                                                                                     
                                                                                     
20:233   5/ 5 [Done                                  ] SDP: done                     


```

rm appeared to reboot then returned to being stuck on 'is starting' page - how do I know if the recovery image is loaded successfully?

**Comment by Eeems** [comment]
Try to connect in the next steps.

**Comment by lemonlemming** [comment]
when I try to run 
`screen /dev/tty.usbmodem1A1103`
I get directory not found

Is this the correct next step and if so how do I find the correct path for my device?

**Comment by Eeems** [comment]
So you are on macOS?

**Comment by lemonlemming** [comment]
correct

**Comment by Eeems** [comment]
Arm or intel?

As for the location, I wouldn't know, as I don't have a mac to try on. You can run `ls -l /dev/tty.usbmodem*` to see if there are other devices listed.

**Comment by lemonlemming** [comment]
intel mac. was able to find the path using the command you suggested thanks

now that I'm logged into the recovery in root how do I proceed? I'm struggling to understand the next steps from the readme sorry

**Comment by Eeems** [comment]
As I don't know what you are trying to accomplish, or what the issue was that caused you to need to do recovery, I don't know what your next steps need to be.

https://github.com/ddvk/remarkable-uuuflash?tab=readme-ov-file#mount-flash-memory

This outlines how to get into the actual device system. Depending on which partition is the current active one, `mount /dev/mmcblk1p2 /mnt/` may need to be `mount /dev/mmcblk1p3 /mnt/` instead.

**Comment by lemonlemming** [comment]
Hi - I'm the person from this thread  https://github.com/ddvk/remarkable-hacks/issues/535

**Comment by Eeems** [comment]
Alright, you'll want to mount the partitions and chroot in like it explains, and then check the logs with `journalctl -b` and look for what it's failing at, and then clean things up. Since it looks like you installed remarkable_entware instead of using toltec, and manually installed other things, I have no idea what your system looks like, and what needs to be removed from the root partition to fix it.

It would probably be easier to just use `upgrade.uuu` to replace the root partitions with 2.1.1.3, and then use codexctl to install the version you want.

https://github.com/ddvk/remarkable-uuuflash?tab=readme-ov-file#semi-upgrade-overwriting-the-root-with-version-2113

**Comment by lemonlemming** [comment]
wasn't worried about data loss so went ahead and reflashed and it's working again
thanks for your help
